# Generated by Django 3.2.5 on 2021-07-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0002_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField()),
                ('billing_address', models.CharField(blank=True, max_length=70, null=True)),
                ('biling_city', models.CharField(blank=True, max_length=40, null=True)),
                ('biling_state', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.BigIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoiceline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.invoice')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.track')),
            ],
        ),
    ]
