# Generated by Django 3.2.5 on 2021-07-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210715_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='biling_city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='biling_state',
            new_name='billing_state',
        ),
    ]
