# Generated by Django 3.2.5 on 2021-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210715_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
