# Generated by Django 3.2.5 on 2021-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210715_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='media',
            new_name='mediatype',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='milli_seconds',
            new_name='milliseconds',
        ),
        migrations.AddField(
            model_name='track',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
